### ISSUE TITLE
Dependencies not installing correctly

### ISSUE THREAD

**Issue by sollenne** [contentful/contentful_jekyll_examples#1]
There may be an error in the dependency location, but I can't quite figure out what is going wrong here. After running the initial block of code in the terminal, I get an error. It looks like you don't have the directories structured just right.

`/Users/RichSollenne/Desktop/mapper/contentful_jekyll_examples/examples/custom_mapper/example/_plugins/mappers.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-contentful-data-import/mappers' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!` 

Do  I need to move something around in my directory? As far as I can tell, everything is untouched from this repo.

**Comment by dlitvakb** [comment]
Hey @sollenne,

If you're intending to run the **Custom Mapper** example, you need to do some extra work. That which is described in the example itself [here](https://github.com/contentful/contentful_jekyll_examples/tree/master/examples/custom_mapper#caveats) and on the `jekyll-contentful-data-import` gem [here](https://github.com/contentful/jekyll-contentful-data-import#caveats). _Note: Both links are contain the same content, just located on different locations._

Sadly, Jekyll by itself doesn't allow to import custom code within the Jekyll application, and that's why this workaround is required.

Hope this helps,

Cheers

**Comment by sollenne** [comment]
@dlitvakb I went back and compared my local environment with the readme doc. The only difference is that I had to install the 'rake' gem. It's still not working. 

On a related note. I tried the get the 'single_space' example and I'm getting a new error.

`fatal: 'jekyll contentful' could not be found. You may need to install the jekyll-contentful gem or a related gem to be able to use this subcommand.`

I seem to already have the `jekyll-contentful` gem and including it in the gemfile does not work. I really want to use contentful, but I'm having a hard time getting it running and an even harder time finding an example repo of someone who has successfully used these plugins.

**Comment by dlitvakb** [comment]
Hey @sollenne,

Can you copy here the exact commands you are running?

Also, `jekyll-contentful` is not the gem required for this to work, you need `jekyll-contentful-data-import`.

Also, if you go to the example directory, and run `bundle install` you should get all the dependencies installed properly. You can follow the instructions in the example folder on how to get the example running. In fact, it's extracted to a single copy-pastable command:

``` bash
echo "Checkout Repository"         && git clone git@github.com:contentful/contentful_jekyll_examples.git && \
echo "Go to This Example's Folder" && cd contentful_jekyll_examples/examples/custom_mapper/example && \
echo "Install Dependencies"        && bundle install && \
echo "Fetch Contentful Data"       && bundle exec rake contentful && \
echo "Start Jekyll Server"         && jekyll server
```

Hope this helps

Cheers

**Comment by sollenne** [comment]
I ran those instructions verbatim 

#### Make the Directory

```
RichSollenne@Richs-MacBook-Pro:~/desktop$ mkdir cful && cd cful
RichSollenne@Richs-MacBook-Pro:~/desktop/cful
```

#### Run the commands in the `readMe`

```
echo "Checkout Repository" && git clone git@github.com:contentful/contentful_jekyll_examples.git && \ 
echo "Go to This Example's Folder" && cd contentful_jekyll_examples/examples/custom_mapper/example && \ 
echo "Install Dependencies"        && bundle install && \
echo "Fetch Contentful Data"       && bundle exec rake contentful && \
echo "Start Jekyll Server"         && jekyll server
```

#### Output

```
Checkout Repository
Cloning into 'contentful_jekyll_examples'...
remote: Counting objects: 120, done.
remote: Total 120 (delta 0), reused 0 (delta 0), pack-reused 120
Receiving objects: 100% (120/120), 28.59 KiB | 0 bytes/s, done.
Resolving deltas: 100% (38/38), done.
Checking connectivity... done.
```

#### `Checkout Repository` Complete (step 1)

```
Go to This Example's Folder
```

#### `Go to This Example's Folder` Complete (step 2)

```
Install Dependencies
Using rake 11.1.2
Using addressable 2.4.0
Using colorator 0.1
Using unf_ext 0.0.7.1
Using http-form_data 1.0.1
Using http_parser.rb 0.6.0
Using multi_json 1.11.2
Using inifile 3.0.0
Using ffi 1.9.10
Using sass 3.4.20
Using rb-fsevent 0.9.6
Using kramdown 1.9.0
Using liquid 3.0.6
Using mercenary 0.3.5
Using rouge 1.10.1
Using safe_yaml 1.0.4
Using bundler 1.11.2
Using launchy 2.4.3
Using unf 0.1.4
Using rb-inotify 0.9.5
Using jekyll-sass-converter 1.3.0
Using domain_name 0.5.25
Using listen 3.0.5
Using http-cookie 1.0.2
Using jekyll-watch 1.3.0
Using http 0.9.8
Using jekyll 3.0.1
Using contentful 0.8.0
Using contentful-management 0.7.3
Using jekyll-contentful-data-import 1.0.1
Using contentful_bootstrap 3.0.0
Bundle complete! 4 Gemfile dependencies, 31 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

#### `Install Dependencies` (`bundle install`) complete (step 3)

```
Fetch Contentful Data
Configuration file:     /Users/RichSollenne/Desktop/cful/contentful_jekyll_examples/examples/custom_mapper/example/_config.yml
Starting Contentful import 
Contentful import finished 
```

#### `Fetch Contentful Data` complete (step 4)

```
Start Jekyll Server
Configuration file: /Users/RichSollenne/Desktop/cful/contentful_jekyll_examples/examples/custom_mapper/example/_config.yml
```

##### Here's there error

```
Dependency Error: Yikes! It looks like you don't have     /Users/RichSollenne/Desktop/cful/contentful_jekyll_examples/examples/custom_mapper/example/_plugins/mappers.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-contentful-data-import/mappers' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.1.2 | Error:      /Users/RichSollenne/Desktop/cful/contentful_jekyll_examples/examples/custom_mapper/example/_plugins/mappers.rb
```

**Comment by dlitvakb** [comment]
Can you please attach the following things?
- The result of: `bundle exec gem list` running inside the `custom_mapper/example` folder
- The result of: `bundle exec ruby --version` on the same folder
- The content of the 2 files that should be located under `/example/_plugins/` in the custom mapper example folder
- The content of the `Rakefile` inside the custom mapper example folder

Cheers

**Comment by sollenne** [comment]
> The result of: `bundle exec gem list` running inside the `custom_mapper/example` folder

```
*** LOCAL GEMS ***

addressable (2.4.0)
bundler (1.11.2)
colorator (0.1)
contentful (0.8.0)
contentful-management (0.7.3)
contentful_bootstrap (3.0.0)
domain_name (0.5.25)
ffi (1.9.10)
http (0.9.8)
http-cookie (1.0.2)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
inifile (3.0.0)
jekyll (3.0.1)
jekyll-contentful-data-import (1.0.1)
jekyll-sass-converter (1.3.0)
jekyll-watch (1.3.0)
kramdown (1.9.0)
launchy (2.4.3)
liquid (3.0.6)
listen (3.0.5)
mercenary (0.3.5)
multi_json (1.11.2)
rake (11.1.2)
rb-fsevent (0.9.6)
rb-inotify (0.9.5)
rouge (1.10.1)
safe_yaml (1.0.4)
sass (3.4.20)
unf (0.1.4)
unf_ext (0.0.7.1)
```

---

> The result of: `bundle exec ruby --version` on the same folder

```
version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```

---

> The content of the 2 files that should be located under `/example/_plugins/` in the custom mapper example folder

##### `/example/_plugins/mappers.rb`

```
require './_plugins/my_reverse_mapper'
```

##### `/example/_plugins/my_reverse_mappers.rb`

```
require 'jekyll-contentful-data-import/mappers'

class MyReverseMapper < Jekyll::Contentful::Mappers::Base
  def map
    result = super
    result.keys.each do |name|
      result[name.reverse] = result[name]
    end

    result
  end
end
```

---

> The content of the `Rakefile` inside the custom mapper example folder

```
require 'jekyll'
require 'jekyll-contentful-data-import'
require './_plugins/mappers'

desc "Import Contentful Data with Custom Mappers"
task :contentful do
  Jekyll::Commands::Contentful.process([], {}, Jekyll.configuration['contentful'])
 end
```

**Comment by sollenne** [comment]
@dlitvakb Just out of curiosity... Do the steps in the readme work for you locally from scratch?

**Comment by dlitvakb** [comment]
@sollenne Yes, they do work, looks like it could be due to the last command not being bundled. The error is coming from `Jekyll 3.1.2` while the version in the `gem list` command is `Jekyll 3.0.1`.

Can you try replacing the last command to `bundle exec jekyll server`?

That might solve it, if so, I'll update the examples accordingly.

Cheers

**Comment by sollenne** [comment]
That seemed to do the trick. I appreciate the help more than you know.

**Comment by dlitvakb** [comment]
Hey @sollenne,

Glad it helped, I'll update the examples to also bundle the server execution.

Cheers
