### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by sgdavis1** [contentful/contentful_jekyll_examples#2]
I was testing out a setup with jekyll+contentful today and cannot get a basic example to work.

I have the `jekyll-contentful-data-import` gem installed without issue but when I try to run it, configured for my "example space" which was setup as the included Contentful example with minor modifications, I am getting a stack level too deep error: 

```
$ bundle exec jekyll contentful
Configuration file: /home/sgdavis/jekyll/northcorridorparents.org/ncp/_config.yml
Starting Contentful import 
/home/sgdavis/.gem/ruby/2.0.0/gems/jekyll-contentful-data-import-1.2.1/lib/jekyll-contentful-data-import/mappers/base.rb:82: stack level too deep (SystemStackError)
```

Any thoughts before I start to dig into the source? Thanks!

**Comment by sgdavis1** [comment]
Maybe it has something to do with the fact that a "Author" has a "Created Posts" value and therefore the nesting is getting expanded infinitely (as a "Post" similarly has an "Author")...

**Comment by dlitvakb** [comment]
Hey @sgdavis1,

Yes, that's exactly it, having circular references, makes the underlying `contentful.rb` gem recurse infinitely.

If you remove your circular reference in the Content Type, you will be able to render without problems.

**Comment by sgdavis1** [comment]
Ahh... guess I should have played around on Contentful a little more first. Obviously it doesn't make a lot of sense to render that default space into the example Jekyll site anyway but I just wanted to try it out and I only had a few minutes to get everything setup. I'll adjust or add a new space and actually create some useful jekyll templates and I'm sure that will solve all my problems. Thanks for the clarification.

Just curious though -- given that the example space has this circular reference -- any ideas on how to handle this if I did actually intend it? Custom Mapper to output the "name" for the referenced item?

**Comment by dlitvakb** [comment]
A custom mapper that handles references differently should definitely do the trick.

The method you should override is `#map_entry`

**Comment by sgdavis1** [comment]
Awesome, I'll give that a try. Thanks for pointing me in the right direction!

**Comment by dlitvakb** [comment]
No problem! Glad to help
